version: '3.1'

services:
  server-ai:
    container_name: betterme-imagecaption
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"